#nodeport pour minikube

namespace: ""

web:
  replicaCount: 1
  repository: icedrus/web-dev
  tag: latest
  command: ["bash", "-c"]
  args: ["uvicorn app.main:app --host 0.0.0.0"]
  containerPort: 8000
  #service:
    #type: ClusterIP
    #port: 8000
    #targetPort: 8000
  service:
    type: NodePort
    port: 8000
    targetPort: 8000
    nodePort: 30081
  config:
    script_name: /api/admin
  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

db:
  replicaCount: 1
  repository: postgres
  tag: 15-alpine
  service:
    #type: ClusterIP
    type: NodePort
    port: 5432
    targetPort: 5432
    nodePort: 30082
  storage:
    capacity: 10Gi
  config:
    db_name: fastapi_traefik
  credentials:
    secret_file: db-secret


traefik:
  replicaCount: 1
  image:
    repository: traefik
    tag: v2.9.6
    pullPolicy: IfNotPresent
  serviceAccountName: traefik-service-account
  args:
    - "--log.level=DEBUG"
    - "--accesslog=true"
    # - "--api.insecure=true"
    - "--api.dashboard=true"
    - "--providers.kubernetescrd=true"
    - "--entrypoints.web.Address=:80"
    - "--entrypoints.websecure.Address=:443"
    # Pour HTTPS
    - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
    - "--certificatesresolvers.letsencrypt.acme.email=josmartosmol@gmail.com"
    - "--certificatesresolvers.letsencrypt.acme.storage=/acme.json"
  ports:
    web:
      containerPort: 80
      nodePort: 30083
    websecure:
      containerPort: 443
      nodePort: 30444
    dashboard:
      containerPort: 8080
      nodePort: 30084


role:
  name: traefik-role
  rules:
    - apiGroups:
        - ""
      resources:
        - services
        - endpoints
        - secrets
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - extensions
        - networking.k8s.io
      resources:
        - ingresses
        - ingressclasses
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - extensions
        - networking.k8s.io
      resources:
        - ingresses/status
      verbs:
        - update
    - apiGroups:
        - traefik.containo.us
      resources:
        - middlewares
        - ingressroutes
        - tlsstores
        - tlsOptions
        - ingressroutetcps
        - ingressrouteudps
        - serverstransports
        - traefikservices
        - middlewaretcps
        - tlsoptions
      verbs:
        - get
        - list
        - watch

serviceAccount:
  name: traefik-service-account

roleBinding:
  name: traefik-role-binding

dashboardService:
  name: traefik-dashboard-service
  #type: LoadBalancer
  #port: 8080
  #targetPort: 8080
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30085

webService:
  name: traefik-web-service
  #type: LoadBalancer
  #port: 80
  #targetPort: 80
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30086

webSecureService:
  name: traefik-websecure-service
  #type: LoadBalancer
  #port: 443
  #targetPort: 443
  type: NodePort
  port: 443
  targetPort: 443
  nodePort: 30446


ingress:
  host: # a definir

secrets:
  web:
    secret_key: ""
  pgadmin:
    email: ""
    password: ""
  db:
    user: ""
    password: ""